<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>901fdbe8-9ae4-45a2-8234-64032f0becab</elementGuidId>
    <imagePath></imagePath>
    <name>button_filterPanel2</name>
    <selectorCollection>
        <entry>
            <key>CSS</key>
            <value>[id="ConnectOpportunitiesAssistant-ConnectableBusinessOpportunitiesList-toggleFilterPane-fndListFilterButton-fndButton-button"]</value>
        </entry>
        <entry>
            <key>XPATH</key>
            <value>//body/fnd-app[1]/fnd-shell[1]/div[1]/fnd-modal-assistant[1]/fnd-dialog-container[1]/div[1]/div[2]/div[2]/fnd-assistant[1]/div[1]/div[1]/div[2]/div[1]/div[2]/div[1]/fnd-container[1]/fnd-list[1]/fnd-collapsible-group[1]/div[1]/div[1]/div[1]/fnd-data-list[1]/div[2]/div[1]/fnd-data-grid-toolbar[1]/div[1]/fnd-toolbar[1]/div[1]/fnd-dynamic-toolbar[1]/fnd-overflow-container[1]/fnd-overflow-container[1]/fnd-overflow-container[1]/fnd-measure[1]/fnd-list-filter-button[1]/div[1]/fnd-granite-button-wrapper[1]/button[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@title,'Filter Panel')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>CSS</selectorMethod>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>false</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>granite-button-base granite-button-wrapper granite-button granite-flat-button ng-star-inserted</value>
        <webElementGuid>30bd2636-b893-46cf-b979-1d33007ac79b</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>false</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>ConnectOpportunitiesAssistant-ConnectableBusinessOpportunitiesList-toggleFilterPane-fndListFilterButton-fndButton-button</value>
        <webElementGuid>30bd2636-b893-46cf-b979-1d33007ac79b</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>Filter Panel</value>
        <webElementGuid>30bd2636-b893-46cf-b979-1d33007ac79b</webElementGuid>
    </webElementProperties>
</WebElementEntity>