<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>77a1a457-c017-45a0-9ce2-55dae8c1d316</elementGuidId>
    <imagePath></imagePath>
    <name>button_delete</name>
    <selectorCollection>
        <entry>
            <key>CSS</key>
            <value>[class="granite-button-base\ granite-button-wrapper\ granite-button\ granite-primary-button\ ng-star-inserted"]</value>
        </entry>
        <entry>
            <key>XPATH</key>
            <value>//body/fnd-app[1]/fnd-shell[1]/div[1]/fnd-message-box[1]/div[2]/div[2]/div[2]/div[3]/fnd-granite-button-wrapper[1]/button[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'button') and equals(@class,'granite-button-base granite-button-wrapper granite-button granite-primary-button ng-star-inserted') and equals(@text,'Delete')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>CSS</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:label=\"Delete Record\"s &gt;&gt; #button &gt;&gt; nth=0</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>granite-button-base granite-button-wrapper granite-button granite-primary-button ng-star-inserted</value>
        <webElementGuid>e2db0501-2c78-406f-8baf-49615b148ebe</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>button</value>
        <webElementGuid>e2db0501-2c78-406f-8baf-49615b148ebe</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Delete</value>
        <webElementGuid>e2db0501-2c78-406f-8baf-49615b148ebe</webElementGuid>
    </webElementProperties>
</WebElementEntity>