<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>------------------------------------------------
 Date       Sign        History
---------  --------   ------------------------
 YYMMDD  UserID  Details
-----------------------------------------------</description>
   <name>obj_btnLogin</name>
   <tag></tag>
   <elementGuidId>1169537e-3a28-48f6-837b-7d2763127f58</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#id-ifs-login-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='id-ifs-login-btn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ced1145b-5a17-4571-be58-1f478a43318c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>a10bc824-c2cb-4484-bdfe-0fea2b524f21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ifs-btn ifs-sign-in-btn ifs-is-desktop</value>
      <webElementGuid>ead9c207-3fe8-47aa-9766-8909543e2801</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>login</value>
      <webElementGuid>ea232437-47cc-4502-83a2-4cf9183bc9bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id-ifs-login-btn</value>
      <webElementGuid>ff98f0d4-af70-4287-915e-8df3f4dba177</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>2c297c80-8aaa-48b4-b2d3-d9ee822ccef1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Log in</value>
      <webElementGuid>021f0d73-ba28-4769-8744-d4a5c39f8051</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id-ifs-login-btn&quot;)</value>
      <webElementGuid>b11be3a5-ba9b-46c0-9f4d-e7948c03dbd0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='id-ifs-login-btn']</value>
      <webElementGuid>9c3c3b17-28e5-4f20-abdd-0d8764653cc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kc-form-buttons']/input</value>
      <webElementGuid>3c32d98e-375b-43b4-a1a3-41b6e3627ca1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>4a6e9722-bfe0-4b6b-808a-f79a94fbfe7a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
