<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>textarea_search</name>
   <tag></tag>
   <elementGuidId>a021c95e-1ada-466b-813d-d652066f5830</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/fnd-app[1]/fnd-shell[1]/div[1]/div[3]/fnd-splitter[1]/div[1]/div[1]/div[1]/div[1]/section[1]/div[2]/div[1]/fnd-search-panel[1]/div[1]/div[1]/div[2]/div[2]/div[1]/textarea[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[equals(@title,'Ctrl+Enter to search') and equals(@type,'text')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[class="ng-tns-c2368425041-9\ ng-pristine\ ng-valid\ ng-touched"]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>textarea[title=\"Ctrl\\+Enter to search\"]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-tns-c2368425041-9 ng-pristine ng-valid ng-touched</value>
      <webElementGuid>ce743a67-f8d6-4398-9a64-18f996fa3314</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Ctrl+Enter to search</value>
      <webElementGuid>ce743a67-f8d6-4398-9a64-18f996fa3314</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ce743a67-f8d6-4398-9a64-18f996fa3314</webElementGuid>
   </webElementProperties>
</WebElementEntity>
