<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>button_testConnection</name>
   <tag></tag>
   <elementGuidId>f1bafe3a-35cf-4b71-87ff-2791e381a0b3</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/div[1]/div[11]/div[1]/div[1]/div[1]/div[6]/fnd-granite-button-wrapper[1]/button[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[equals(@title,'Test Connection') and equals(@text,'Test Connection')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[id="PsoIntegrationConfigurations-PsoIntegrationConfigurations-fndRow-1-fndCommandCell-fndCommandDropdown-fndMenu-fndButton-PsoIntegrationConfigurations_CommandTestConnection-button"]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#PsoIntegrationConfigurations-PsoIntegrationConfigurations-fndRow-1-fndCommandCell-fndCommandDropdown-fndMenu-fndButton-PsoIntegrationConfigurations_CommandTestConnection-button</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>granite-button-base granite-button-wrapper granite-button ng-star-inserted</value>
      <webElementGuid>5714b90b-59ba-4213-9ca5-c17d0766999b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Test Connection</value>
      <webElementGuid>5714b90b-59ba-4213-9ca5-c17d0766999b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Test Connection</value>
      <webElementGuid>5714b90b-59ba-4213-9ca5-c17d0766999b</webElementGuid>
   </webElementProperties>
</WebElementEntity>
