<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>button_search2</name>
   <tag></tag>
   <elementGuidId>84467d32-ee59-41eb-b58d-e4d5915fbe8e</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/fnd-app[1]/fnd-shell[1]/div[1]/div[3]/fnd-splitter[1]/div[1]/div[1]/div[1]/div[1]/section[1]/div[2]/div[1]/fnd-search-panel[1]/div[1]/div[1]/div[2]/div[2]/fnd-search-actions-panel[1]/div[1]/fnd-search-action-button[1]/button[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[equals(@title,'Search') and equals(@text,'Search')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>.advanced-search &gt; .actions-pane .granite-button-base</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>button[title=\"Search\"] &gt;&gt; nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>granite-button-base search-button granite-primary-button</value>
      <webElementGuid>ce743a67-f8d6-4398-9a64-18f996fa3314</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>ce743a67-f8d6-4398-9a64-18f996fa3314</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>ce743a67-f8d6-4398-9a64-18f996fa3314</webElementGuid>
   </webElementProperties>
</WebElementEntity>
