<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>input_description_1</name>
   <tag></tag>
   <elementGuidId>484d0505-69af-435a-93d1-584994c5ca8b</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/fnd-app[1]/fnd-shell[1]/div[1]/fnd-modal-dialog[1]/fnd-dialog-container[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[1]/fnd-group[1]/fnd-collapsible-group[1]/div[1]/div[1]/div[1]/fnd-input-field-container[2]/fnd-input-field[1]/div[1]/form[1]/div[2]/div[1]/div[1]/input[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[equals(@type,'text') and equals(@role,'textbox')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[class="ng-tns-c1728421794-1575\ ifs-field\ ifs-field-hover\ edit-mode\ editable\ ng-untouched\ ng-pristine\ ng-valid\ ng-star-inserted"]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#modalDialogComponent-NewMarketingCampaignGroup-Description &gt;&gt; internal:label=\"Description\"s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-tns-c1728421794-1575 ifs-field ifs-field-hover edit-mode editable ng-untouched ng-pristine ng-valid ng-star-inserted</value>
      <webElementGuid>ce743a67-f8d6-4398-9a64-18f996fa3314</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>ce743a67-f8d6-4398-9a64-18f996fa3314</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ce743a67-f8d6-4398-9a64-18f996fa3314</webElementGuid>
   </webElementProperties>
</WebElementEntity>
