<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>item_sjStephenJeffsWatts</name>
   <tag></tag>
   <elementGuidId>aa2055e7-30a9-4eef-b6e4-d1f5fc39f3a9</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/fnd-app[1]/fnd-shell[1]/div[1]/fnd-modal-dialog[1]/fnd-dialog-container[1]/div[1]/fnd-adjacent-container[1]/div[1]/fnd-adjacent-content[1]/fnd-keep-within-viewport[1]/div[1]/div[1]/fnd-lov[1]/div[1]/div[1]/nav[1]/ul[1]/li[2]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[equals(@text,'SJ
         Stephen Jeffs-Watts(Name)
         STEJ(Representative ID)
         (No value)(Role)') and equals(@role,'option')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>.selector-lov-row</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#modalDialogComponent-NewMarketingCampaignGroup-MainRepresentativeId-lovContainerComponent-lovComponent-lov-row-0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selector-lov-row ng-star-inserted selected-lov-row</value>
      <webElementGuid>5714b90b-59ba-4213-9ca5-c17d0766999b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>5714b90b-59ba-4213-9ca5-c17d0766999b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SJ
      Stephen Jeffs-Watts(Name)
      STEJ(Representative ID)
      (No value)(Role)</value>
      <webElementGuid>5714b90b-59ba-4213-9ca5-c17d0766999b</webElementGuid>
   </webElementProperties>
</WebElementEntity>
