<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>99f70c7b-a009-49b6-9c5e-5b15c5dcd2d5</elementGuidId>
    <imagePath></imagePath>
    <name>item_swiftcareHealthSolutions</name>
    <selectorCollection>
        <entry>
            <key>CSS</key>
            <value>.selected-lov-row</value>
        </entry>
        <entry>
            <key>XPATH</key>
            <value>//body/fnd-app[1]/fnd-shell[1]/div[1]/div[3]/fnd-splitter[1]/div[1]/div[1]/div[1]/div[1]/section[1]/div[2]/fnd-page[1]/fnd-param-sheet-dialog[1]/fnd-dialog-container[1]/div[1]/fnd-adjacent-container[1]/div[1]/fnd-adjacent-content[1]/fnd-keep-within-viewport[1]/div[1]/div[1]/fnd-lov[1]/div[1]/div[1]/nav[1]/ul[1]/li[5]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'Swiftcare Health Solutions(Account)
            (No value)(Description)
            Antony Bourne(Contact Name)') and equals(@role,'option')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>CSS</selectorMethod>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>false</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>selector-lov-row ng-star-inserted selected-lov-row</value>
        <webElementGuid>30bd2636-b893-46cf-b979-1d33007ac79b</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>role</name>
        <type>Main</type>
        <value>option</value>
        <webElementGuid>30bd2636-b893-46cf-b979-1d33007ac79b</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Swiftcare Health Solutions(Account)
        (No value)(Description)
        Antony Bourne(Contact Name)</value>
        <webElementGuid>30bd2636-b893-46cf-b979-1d33007ac79b</webElementGuid>
    </webElementProperties>
</WebElementEntity>