<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>label_conference</name>
   <tag></tag>
   <elementGuidId>ffb157b9-6a86-4d6d-94a7-ba1486a3fce4</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/fnd-app[1]/fnd-shell[1]/div[1]/fnd-modal-dialog[1]/fnd-dialog-container[1]/div[1]/fnd-adjacent-container[1]/div[1]/fnd-adjacent-content[1]/fnd-keep-within-viewport[1]/div[1]/div[1]/fnd-dropdown[1]/fnd-menu[1]/ul[1]/li[1]/fnd-menu-select-item[1]/div[1]/fnd-menu-item[1]/div[1]/label[1]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>.item-label</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = ' Conference ' or . = ' Conference ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>label >> internal:text=&quot;Conference&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>item-label ng-star-inserted</value>
      <webElementGuid>7be4753d-690c-4bed-a644-7941658230ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Conference </value>
      <webElementGuid>7be4753d-690c-4bed-a644-7941658230ca</webElementGuid>
   </webElementProperties>
</WebElementEntity>
