<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>link_details</name>
   <tag></tag>
   <elementGuidId>76af5269-6b8f-43ae-9da7-d0be20091b9c</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/fnd-app[1]/fnd-shell[1]/div[1]/div[3]/fnd-splitter[1]/div[1]/div[1]/div[1]/div[1]/section[1]/div[2]/fnd-page[1]/div[1]/fnd-splitter[1]/div[2]/div[2]/div[2]/fnd-container[1]/fnd-tab-container[1]/fnd-tab-control[1]/div[1]/fnd-tab-content[4]/fnd-container[1]/fnd-list[1]/fnd-collapsible-group[1]/div[1]/div[1]/div[1]/fnd-data-list[1]/div[2]/div[1]/fnd-data-grid-toolbar[1]/div[1]/fnd-toolbar[1]/div[1]/fnd-dynamic-toolbar[1]/fnd-overflow-container[1]/fnd-overflow-container[1]/fnd-overflow-container[3]/fnd-measure[1]/span[1]/fnd-granite-button-wrapper[1]/a[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[equals(@title,'Go to details') and equals(@text,'Details')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[class="granite-button-base\ granite-button-anchor-wrapper\ granite-button\ granite-flat-button\ ng-star-inserted"]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>a[title=\"Go to details\"]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>granite-button-base granite-button-anchor-wrapper granite-button granite-flat-button ng-star-inserted</value>
      <webElementGuid>5714b90b-59ba-4213-9ca5-c17d0766999b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Form-MarketingListTabList-fndDataGridToolbar-fndToolbar-action-detail-fndButton-button</value>
      <webElementGuid>5714b90b-59ba-4213-9ca5-c17d0766999b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Details</value>
      <webElementGuid>5714b90b-59ba-4213-9ca5-c17d0766999b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Go to details</value>
      <webElementGuid>5714b90b-59ba-4213-9ca5-c17d0766999b</webElementGuid>
   </webElementProperties>
</WebElementEntity>
