<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>link_ifsiCloud</name>
   <tag></tag>
   <elementGuidId>15847c11-96cb-45af-bed7-7ec2258794c3</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/div[1]/div[1]/main[1]/nav[1]/ul[1]/li[1]/a[1]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(1) > [class=&quot;_application_1sb1q_2\ _tile_1sb1q_2&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@href = '/main/ifsapplications/web' and (text() = 'IFSI F SCloudIFS...[truncated lines=10]' or . = 'IFSI F SCloudIFS...[truncated lines=10]')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>a >> internal:text=&quot;IFSI F S CloudIFSI F S Cloud employee solutionsSign intrending-neutral&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>action-49e93528-4e16-433b-827c-44049b52529d</value>
      <webElementGuid>82df2f8d-983c-4047-9493-4fae74125ee3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_application_1sb1q_2 _tile_1sb1q_2</value>
      <webElementGuid>82df2f8d-983c-4047-9493-4fae74125ee3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/main/ifsapplications/web</value>
      <webElementGuid>82df2f8d-983c-4047-9493-4fae74125ee3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>style</name>
      <type>Main</type>
      <value>--category-foreground-color:var(--granite-color-background-categorical-2);--category-background-color:var(--granite-color-categorical-2)</value>
      <webElementGuid>82df2f8d-983c-4047-9493-4fae74125ee3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>IFSI F SCloudIFS...[truncated lines=10]</value>
      <webElementGuid>82df2f8d-983c-4047-9493-4fae74125ee3</webElementGuid>
   </webElementProperties>
</WebElementEntity>
