<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>53e9e986-da2f-4926-9b7d-8d06aa722f8a</elementGuidId>
    <imagePath></imagePath>
    <name>item_service</name>
    <selectorCollection>
        <entry>
            <key>CSS</key>
            <value>.selector-lov-row</value>
        </entry>
        <entry>
            <key>XPATH</key>
            <value>//body/fnd-app[1]/fnd-shell[1]/div[1]/fnd-adjacent-container[1]/div[1]/fnd-adjacent-content[1]/fnd-keep-within-viewport[1]/div[1]/div[1]/fnd-lov[1]/div[1]/div[1]/nav[1]/ul[1]/li[2]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'Service(Competitive Advantage Description)') and equals(@role,'option')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>CSS</selectorMethod>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>false</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>selector-lov-row ng-star-inserted selected-lov-row</value>
        <webElementGuid>3fbe5ab4-dbc2-4862-9285-5838d2c11232</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>role</name>
        <type>Main</type>
        <value>option</value>
        <webElementGuid>3fbe5ab4-dbc2-4862-9285-5838d2c11232</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Service(Competitive Advantage Description)</value>
        <webElementGuid>3fbe5ab4-dbc2-4862-9285-5838d2c11232</webElementGuid>
    </webElementProperties>
</WebElementEntity>