<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>948e1d09-bc63-4d7b-b69c-67a7d31eca8e</elementGuidId>
    <imagePath></imagePath>
    <name>button_search</name>
    <selectorCollection>
        <entry>
            <key>CSS</key>
            <value>.advanced-search &gt; .actions-pane .granite-button-base</value>
        </entry>
        <entry>
            <key>XPATH</key>
            <value>//body/fnd-app[1]/fnd-shell[1]/div[1]/div[3]/fnd-splitter[1]/div[1]/div[1]/div[1]/div[1]/section[1]/div[2]/div[1]/fnd-search-panel[1]/div[1]/div[1]/div[2]/div[2]/fnd-search-actions-panel[1]/div[1]/fnd-search-action-button[1]/button[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@title,'Click to update page search results') and equals(@text,'Search')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>CSS</selectorMethod>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>false</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>granite-button-base search-button granite-primary-button</value>
        <webElementGuid>3fbe5ab4-dbc2-4862-9285-5838d2c11232</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Search</value>
        <webElementGuid>3fbe5ab4-dbc2-4862-9285-5838d2c11232</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>Click to update page search results</value>
        <webElementGuid>3fbe5ab4-dbc2-4862-9285-5838d2c11232</webElementGuid>
    </webElementProperties>
</WebElementEntity>