<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>2c6e1a0e-40ed-4c83-8771-3af232c55f0a</elementGuidId>
    <imagePath></imagePath>
    <name>item_selectedOption</name>
    <selectorCollection>
        <entry>
            <key>CSS</key>
            <value>.selector-lov-row</value>
        </entry>
        <entry>
            <key>XPATH</key>
            <value>//body/fnd-app[1]/fnd-shell[1]/div[1]/fnd-adjacent-container[1]/div[1]/fnd-adjacent-content[1]/fnd-keep-within-viewport[1]/div[1]/div[1]/fnd-lov[1]/div[1]/div[1]/nav[1]/ul[1]/li[2]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'JA
            JABR(Person ID)
            James Brown(Name)') and equals(@role,'option')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>CSS</selectorMethod>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>false</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>selector-lov-row ng-star-inserted selected-lov-row</value>
        <webElementGuid>30bd2636-b893-46cf-b979-1d33007ac79b</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>role</name>
        <type>Main</type>
        <value>option</value>
        <webElementGuid>30bd2636-b893-46cf-b979-1d33007ac79b</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>JA
        JABR(Person ID)
        James Brown(Name)</value>
        <webElementGuid>30bd2636-b893-46cf-b979-1d33007ac79b</webElementGuid>
    </webElementProperties>
</WebElementEntity>