<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>link_solutionManagerAutomationOptimization</name>
   <tag></tag>
   <elementGuidId>f1be99a1-4f54-4cab-a555-b935bd1ad7c4</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/fnd-app[1]/fnd-shell[1]/div[1]/div[3]/fnd-splitter[1]/div[1]/div[1]/div[1]/div[1]/fnd-sidebar-container[1]/div[1]/fnd-sidebar[1]/nav[1]/fnd-navigation-menu-controller[1]/fnd-submenu[1]/ul[1]/li[1]/fnd-submenu-selectable-item[1]/div[1]/fnd-submenu-item[1]/div[1]/a[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[equals(@href,'/main/ifsapplications/web/page/PsoIntegrationConfiguration/PsoIntegrationConfigurations;path=0.1656053651.572628553.518637879.1550909469;clearExtras=true') and equals(@text,'Solution Manager / Automation and Optimization / Scheduling Optimization
         Scheduling Optimization Configuration')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>.link-item &gt; [class="ng-star-inserted"]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#fnd-sidebar a</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-star-inserted</value>
      <webElementGuid>5714b90b-59ba-4213-9ca5-c17d0766999b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/main/ifsapplications/web/page/PsoIntegrationConfiguration/PsoIntegrationConfigurations;path=0.1656053651.572628553.518637879.1550909469;clearExtras=true</value>
      <webElementGuid>5714b90b-59ba-4213-9ca5-c17d0766999b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Solution Manager / Automation and Optimization / Scheduling Optimization
      Scheduling Optimization Configuration</value>
      <webElementGuid>5714b90b-59ba-4213-9ca5-c17d0766999b</webElementGuid>
   </webElementProperties>
</WebElementEntity>
