<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>body_idIfsBody</name>
   <tag></tag>
   <elementGuidId>683daff4-72f5-4fd2-990c-e01d124da8ee</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>.ifs-login-body</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'addCustomClassOnDevice(['id-ifs-body']);...[truncated lines=94]' or . = 'addCustomClassOnDevice(['id-ifs-body']);...[truncated lines=94]')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#id-ifs-body</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> ifs-login-body  ifs-is-desktop</value>
      <webElementGuid>3fae6658-a071-4c00-a7f9-bc507e815e51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id-ifs-body</value>
      <webElementGuid>3fae6658-a071-4c00-a7f9-bc507e815e51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onload</name>
      <type>Main</type>
      <value>onLoad('')</value>
      <webElementGuid>3fae6658-a071-4c00-a7f9-bc507e815e51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
    
        addCustomClassOnDevice(['id-ifs-body']);
    
    
...[truncated lines=94]</value>
      <webElementGuid>3fae6658-a071-4c00-a7f9-bc507e815e51</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//body[@id='id-ifs-body']</value>
      <webElementGuid>3fae6658-a071-4c00-a7f9-bc507e815e51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//body</value>
      <webElementGuid>3fae6658-a071-4c00-a7f9-bc507e815e51</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
