<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>083b5fc5-c7bd-4edf-86ea-44fadd1bc4f4</elementGuidId>
    <imagePath></imagePath>
    <name>item_customerCategory</name>
    <selectorCollection>
        <entry>
            <key>CSS</key>
            <value>.selected-lov-row</value>
        </entry>
        <entry>
            <key>XPATH</key>
            <value>//body/fnd-app[1]/fnd-shell[1]/div[1]/fnd-adjacent-container[1]/div[1]/fnd-adjacent-content[1]/fnd-keep-within-viewport[1]/div[1]/div[1]/fnd-lov[1]/div[1]/div[1]/nav[1]/ul[1]/li[5]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'C
            10081(Account No)
            Customer2_1234(Name)
            End Customer(Category)') and equals(@role,'option')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>CSS</selectorMethod>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>false</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>selector-lov-row ng-star-inserted selected-lov-row</value>
        <webElementGuid>ee73da60-be40-4f65-8f74-dbba35950521</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>role</name>
        <type>Main</type>
        <value>option</value>
        <webElementGuid>ee73da60-be40-4f65-8f74-dbba35950521</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>C
        10081(Account No)
        Customer2_1234(Name)
        End Customer(Category)</value>
        <webElementGuid>ee73da60-be40-4f65-8f74-dbba35950521</webElementGuid>
    </webElementProperties>
</WebElementEntity>