<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>item_jaJabr</name>
   <tag></tag>
   <elementGuidId>12ac15ab-16a3-4e2d-98da-18e9dfc62d01</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/fnd-app[1]/fnd-shell[1]/div[1]/fnd-adjacent-container[1]/div[1]/fnd-adjacent-content[1]/fnd-keep-within-viewport[1]/div[1]/div[1]/fnd-lov[1]/div[1]/div[1]/nav[1]/ul[1]/li[2]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>.selector-lov-row</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'JA
         JABR(Person ID)
         James Brown(Name)' or . = 'JA
         JABR(Person ID)
         James Brown(Name)') and @role = 'option']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#AddContactAssistant-ContactDetailGroup-PersonId-lovContainerComponent-lovComponent-lov-row-0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selector-lov-row ng-star-inserted selected-lov-row</value>
      <webElementGuid>7be4753d-690c-4bed-a644-7941658230ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>7be4753d-690c-4bed-a644-7941658230ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>JA
      JABR(Person ID)
      James Brown(Name)</value>
      <webElementGuid>7be4753d-690c-4bed-a644-7941658230ca</webElementGuid>
   </webElementProperties>
</WebElementEntity>
