<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>item_conference</name>
   <tag></tag>
   <elementGuidId>e2610d8a-0834-4c19-9b1a-d00c2d402948</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/fnd-app[1]/fnd-shell[1]/div[1]/fnd-modal-dialog[1]/fnd-dialog-container[1]/div[1]/fnd-adjacent-container[1]/div[1]/fnd-adjacent-content[1]/fnd-keep-within-viewport[1]/div[1]/div[1]/fnd-dropdown[1]/fnd-menu[1]/ul[1]/li[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[equals(@text,' Conference ') and equals(@role,'option')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[role="listbox"] &gt; [class="ng-star-inserted"]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#modalDialogComponent li</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-star-inserted</value>
      <webElementGuid>ce743a67-f8d6-4398-9a64-18f996fa3314</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>ce743a67-f8d6-4398-9a64-18f996fa3314</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Conference </value>
      <webElementGuid>ce743a67-f8d6-4398-9a64-18f996fa3314</webElementGuid>
   </webElementProperties>
</WebElementEntity>
