<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>input_startDate</name>
   <tag></tag>
   <elementGuidId>7409d543-9463-4da6-b704-0fde3dc81c06</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/fnd-app[1]/fnd-shell[1]/div[1]/fnd-modal-dialog[1]/fnd-dialog-container[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[1]/fnd-group[1]/fnd-collapsible-group[1]/div[1]/div[1]/div[1]/fnd-input-field-container[5]/fnd-input-field[1]/div[1]/form[1]/div[2]/div[1]/div[1]/input[1]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[class=&quot;ng-tns-c1728421794-1576\ isDateField\ ifs-field\ ifs-field-hover\ edit-mode\ editable\ haspicker\ ng-untouched\ ng-pristine\ ng-valid\ ng-star-inserted&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'text' and @role = 'textbox']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[id=&quot;\38 41cc000-1833-424e-aa76-e706f6889853&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-tns-c1728421794-1576 isDateField ifs-field ifs-field-hover edit-mode editable haspicker ng-untouched ng-pristine ng-valid ng-star-inserted</value>
      <webElementGuid>7be4753d-690c-4bed-a644-7941658230ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>7be4753d-690c-4bed-a644-7941658230ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7be4753d-690c-4bed-a644-7941658230ca</webElementGuid>
   </webElementProperties>
</WebElementEntity>
