<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>input_mainRepresentative</name>
   <tag></tag>
   <elementGuidId>b5b408a4-6abd-41d7-9386-c1fb243c95cb</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/fnd-app[1]/fnd-shell[1]/div[1]/fnd-modal-dialog[1]/fnd-dialog-container[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[1]/fnd-group[1]/fnd-collapsible-group[1]/div[1]/div[1]/div[1]/fnd-input-field-container[9]/fnd-input-field[1]/div[1]/form[1]/div[2]/div[1]/div[1]/input[1]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[class=&quot;ng-tns-c1728421794-1580\ ifs-field\ ifs-field-hover\ detail-page\ ng-untouched\ ng-pristine\ ng-valid\ edit-mode\ editable\ haspicker\ ng-star-inserted&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'text' and @role = 'combobox']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>input[aria-label=&quot;Main Representative&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-tns-c1728421794-1580 ifs-field ifs-field-hover detail-page ng-untouched ng-pristine ng-valid edit-mode editable haspicker ng-star-inserted</value>
      <webElementGuid>7be4753d-690c-4bed-a644-7941658230ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>7be4753d-690c-4bed-a644-7941658230ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7be4753d-690c-4bed-a644-7941658230ca</webElementGuid>
   </webElementProperties>
</WebElementEntity>
