<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>item_contactOption</name>
   <tag></tag>
   <elementGuidId>a747af04-b942-4c7a-b74e-a9c045b40c19</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/fnd-app[1]/fnd-shell[1]/div[1]/fnd-adjacent-container[1]/div[1]/fnd-adjacent-content[1]/fnd-keep-within-viewport[1]/div[1]/div[1]/fnd-lov[1]/div[1]/div[1]/nav[1]/ul[1]/li[2]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[equals(@text,'contactL_234(Name)
         (No value)(Title)
         (No value)(Role)') and equals(@role,'option')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>.selector-lov-row</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#Form-MarketingListContactsList-fndRow-0-LeadContactRef-InputField-lovContainerComponent-lovComponent-lov-row-0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selector-lov-row ng-star-inserted selected-lov-row</value>
      <webElementGuid>a5439a7e-3c75-4750-8611-c3b6f4c39637</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>a5439a7e-3c75-4750-8611-c3b6f4c39637</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>contactL_234(Name)
      (No value)(Title)
      (No value)(Role)</value>
      <webElementGuid>a5439a7e-3c75-4750-8611-c3b6f4c39637</webElementGuid>
   </webElementProperties>
</WebElementEntity>
