<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>15d3019c-fb3c-44ba-8d72-8b1ba8d196e6</elementGuidId>
    <imagePath></imagePath>
    <name>button_userDropdown</name>
    <selectorCollection>
        <entry>
            <key>CSS</key>
            <value>.user-dropdown</value>
        </entry>
        <entry>
            <key>XPATH</key>
            <value>//body/fnd-app[1]/fnd-shell[1]/div[1]/div[3]/fnd-splitter[1]/div[1]/div[1]/header[1]/button[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'granite-button-base granite-menu-trigger user-dropdown ng-tns-c2309382438-0 granite-toolbar-button') and equals(@text,'IA')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>CSS</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:label=\"Your profile and settings closed\"s</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>granite-button-base granite-menu-trigger user-dropdown ng-tns-c2309382438-0 granite-toolbar-button</value>
        <webElementGuid>e2db0501-2c78-406f-8baf-49615b148ebe</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>IA</value>
        <webElementGuid>e2db0501-2c78-406f-8baf-49615b148ebe</webElementGuid>
    </webElementProperties>
</WebElementEntity>