<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>3e1f23b0-0998-4f24-95cf-3a72a3ba85b9</elementGuidId>
    <imagePath></imagePath>
    <name>input_search</name>
    <selectorCollection>
        <entry>
            <key>CSS</key>
            <value>#searchInputInsideNavigationMenu</value>
        </entry>
        <entry>
            <key>XPATH</key>
            <value>//body/fnd-app[1]/fnd-shell[1]/div[1]/div[3]/fnd-splitter[1]/fnd-sidebar-container[1]/div[1]/fnd-sidebar[1]/nav[1]/fnd-navigation-menu-controller[1]/div[2]/div[1]/input[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@title,'Type to find a page') and equals(@type,'text')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>CSS</selectorMethod>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>false</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>search-field ng-untouched ng-pristine ng-valid</value>
        <webElementGuid>84a4e4a3-b371-4532-9f7e-b9cab76269fb</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>false</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>searchInputInsideNavigationMenu</value>
        <webElementGuid>84a4e4a3-b371-4532-9f7e-b9cab76269fb</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>Type to find a page</value>
        <webElementGuid>84a4e4a3-b371-4532-9f7e-b9cab76269fb</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>text</value>
        <webElementGuid>84a4e4a3-b371-4532-9f7e-b9cab76269fb</webElementGuid>
    </webElementProperties>
</WebElementEntity>