<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>ee78bfe2-0744-48cc-9346-da0ec83ce4cd</elementGuidId>
    <imagePath></imagePath>
    <name>link_navigateToLeadDetail</name>
    <selectorCollection>
        <entry>
            <key>CSS</key>
            <value>li:nth-of-type(5) [class="ng-star-inserted"]</value>
        </entry>
        <entry>
            <key>XPATH</key>
            <value>//body/fnd-app[1]/fnd-shell[1]/div[1]/div[3]/fnd-splitter[1]/fnd-sidebar-container[1]/div[1]/fnd-sidebar[1]/nav[1]/fnd-navigation-menu-controller[1]/fnd-submenu[1]/ul[1]/li[5]/fnd-submenu-selectable-item[1]/div[1]/fnd-submenu-item[1]/div[1]/a[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'/main/ifsapplications/web/page/BusinessLead/BusinessLeadDetailPage;path=0.279000411.615228976.1142250054.2103100803;clearExtras=true') and equals(@text,'Relationship Management / Customer Relationship Management / Lead
            Lead')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>CSS</selectorMethod>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>false</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>ng-star-inserted</value>
        <webElementGuid>84a4e4a3-b371-4532-9f7e-b9cab76269fb</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>/main/ifsapplications/web/page/BusinessLead/BusinessLeadDetailPage;path=0.279000411.615228976.1142250054.2103100803;clearExtras=true</value>
        <webElementGuid>84a4e4a3-b371-4532-9f7e-b9cab76269fb</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Relationship Management / Customer Relationship Management / Lead
        Lead</value>
        <webElementGuid>84a4e4a3-b371-4532-9f7e-b9cab76269fb</webElementGuid>
    </webElementProperties>
</WebElementEntity>