<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>e4abfae4-35f1-470d-b1d2-a2241f95ccd3</elementGuidId>
    <imagePath></imagePath>
    <name>link_schedulingOptimizationConfig</name>
    <selectorCollection>
        <entry>
            <key>CSS</key>
            <value>.link-item &gt; [class="ng-star-inserted"]</value>
        </entry>
        <entry>
            <key>XPATH</key>
            <value>//body/fnd-app[1]/fnd-shell[1]/div[1]/div[3]/fnd-splitter[1]/fnd-sidebar-container[1]/div[1]/fnd-sidebar[1]/nav[1]/fnd-navigation-menu-controller[1]/fnd-submenu[1]/ul[1]/li[1]/fnd-submenu-selectable-item[1]/div[1]/fnd-submenu-item[1]/div[1]/a[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'/main/ifsapplications/web/page/PsoIntegrationConfiguration/PsoIntegrationConfigurations;path=0.1656053651.572628553.518637879.1550909469;clearExtras=true') and equals(@text,'Solution Manager / Automation and Optimization / Scheduling Optimization
            Scheduling Optimization Configuration')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>CSS</selectorMethod>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>false</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>ng-star-inserted</value>
        <webElementGuid>ee73da60-be40-4f65-8f74-dbba35950521</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>/main/ifsapplications/web/page/PsoIntegrationConfiguration/PsoIntegrationConfigurations;path=0.1656053651.572628553.518637879.1550909469;clearExtras=true</value>
        <webElementGuid>ee73da60-be40-4f65-8f74-dbba35950521</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Solution Manager / Automation and Optimization / Scheduling Optimization
        Scheduling Optimization Configuration</value>
        <webElementGuid>ee73da60-be40-4f65-8f74-dbba35950521</webElementGuid>
    </webElementProperties>
</WebElementEntity>