<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>bc031008-28e0-439d-bf9d-713f2d52b6ec</elementGuidId>
    <imagePath></imagePath>
    <name>link_account</name>
    <selectorCollection>
        <entry>
            <key>CSS</key>
            <value>li:nth-of-type(1) [class="ng-star-inserted"]</value>
        </entry>
        <entry>
            <key>XPATH</key>
            <value>//body/fnd-app[1]/fnd-shell[1]/div[1]/div[3]/fnd-splitter[1]/fnd-sidebar-container[1]/div[1]/fnd-sidebar[1]/nav[1]/fnd-navigation-menu-controller[1]/fnd-submenu[1]/ul[1]/li[1]/fnd-submenu-selectable-item[1]/div[1]/fnd-submenu-item[1]/div[1]/a[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'/main/ifsapplications/web/page/CrmCustomer/CrmCustomerPage;path=0.279000411.615228976.64182721.1845772960;clearExtras=true') and equals(@text,'Relationship Management / Customer Relationship Management / Account
            Account - CRM')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>CSS</selectorMethod>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>false</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>ng-star-inserted</value>
        <webElementGuid>3bd89cf4-7f59-42be-aaa7-b057fbbf5ef7</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>/main/ifsapplications/web/page/CrmCustomer/CrmCustomerPage;path=0.279000411.615228976.64182721.1845772960;clearExtras=true</value>
        <webElementGuid>3bd89cf4-7f59-42be-aaa7-b057fbbf5ef7</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Relationship Management / Customer Relationship Management / Account
        Account - CRM</value>
        <webElementGuid>3bd89cf4-7f59-42be-aaa7-b057fbbf5ef7</webElementGuid>
    </webElementProperties>
</WebElementEntity>