<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>1f574657-c8ef-4bb3-95a8-c631edc764a8</elementGuidId>
    <imagePath></imagePath>
    <name>i_collapse9</name>
    <selectorCollection>
        <entry>
            <key>CSS</key>
            <value>.icon-collapse</value>
        </entry>
        <entry>
            <key>XPATH</key>
            <value>//body/fnd-app[1]/fnd-shell[1]/div[1]/div[3]/fnd-splitter[1]/div[1]/div[1]/div[1]/div[1]/section[1]/div[2]/fnd-lobby-page[1]/div[1]/div[2]/div[1]/div[1]/fnd-lobby-renderer[1]/div[1]/div[1]/div[10]/div[1]/fnd-lobby-element[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/i[1]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>CSS</selectorMethod>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>icon-collapse ng-star-inserted</value>
        <webElementGuid>30bd2636-b893-46cf-b979-1d33007ac79b</webElementGuid>
    </webElementProperties>
</WebElementEntity>