<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>4d6ced5b-afc3-4be7-b07a-33f378032209</elementGuidId>
    <imagePath></imagePath>
    <name>i_collapse5_1</name>
    <selectorCollection>
        <entry>
            <key>CSS</key>
            <value>.icon-collapse</value>
        </entry>
        <entry>
            <key>XPATH</key>
            <value>//body/fnd-app[1]/fnd-shell[1]/div[1]/div[3]/fnd-splitter[1]/div[1]/div[1]/div[1]/div[1]/section[1]/div[2]/fnd-lobby-page[1]/div[1]/div[2]/div[1]/div[1]/fnd-lobby-renderer[1]/div[1]/div[1]/div[5]/div[1]/fnd-lobby-element[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/i[1]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>CSS</selectorMethod>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>icon-collapse ng-star-inserted</value>
        <webElementGuid>3bd89cf4-7f59-42be-aaa7-b057fbbf5ef7</webElementGuid>
    </webElementProperties>
</WebElementEntity>