<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>button_delete</name>
   <tag></tag>
   <elementGuidId>6fe8d26b-294f-4303-abf9-0957020c9c5d</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/fnd-app[1]/fnd-shell[1]/div[1]/fnd-message-box[1]/div[2]/div[2]/div[2]/div[3]/fnd-granite-button-wrapper[1]/button[1]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[class=&quot;granite-button-base\ granite-button-wrapper\ granite-button\ granite-primary-button\ ng-star-inserted&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Delete' or . = 'Delete')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#button >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>granite-button-base granite-button-wrapper granite-button granite-primary-button ng-star-inserted</value>
      <webElementGuid>7be4753d-690c-4bed-a644-7941658230ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7be4753d-690c-4bed-a644-7941658230ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Delete</value>
      <webElementGuid>7be4753d-690c-4bed-a644-7941658230ca</webElementGuid>
   </webElementProperties>
</WebElementEntity>
