<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>28f91ea6-49c8-4e6a-8418-c1e8d724572a</elementGuidId>
    <imagePath></imagePath>
    <name>input_description</name>
    <selectorCollection>
        <entry>
            <key>CSS</key>
            <value>[class="ng-tns-c1728421794-1503\ list-field\ ifs-field\ ifs-field-hover\ compact\ edit-mode\ editable\ ng-untouched\ ng-pristine\ ng-valid\ ng-star-inserted"]</value>
        </entry>
        <entry>
            <key>XPATH</key>
            <value>//body/fnd-app[1]/fnd-shell[1]/div[1]/div[3]/fnd-splitter[1]/div[1]/div[1]/div[1]/div[1]/section[1]/div[2]/fnd-page[1]/div[1]/fnd-splitter[1]/div[2]/div[2]/div[1]/fnd-container[1]/fnd-list[1]/fnd-collapsible-group[1]/div[1]/div[1]/div[1]/fnd-data-list[1]/div[3]/div[2]/fnd-row[1]/fnd-cell[2]/fnd-input-field-container[1]/fnd-input-field[1]/div[1]/form[1]/div[2]/div[1]/div[1]/input[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@type,'text') and equals(@role,'textbox')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>CSS</selectorMethod>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>false</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>ng-tns-c1728421794-1503 list-field ifs-field ifs-field-hover compact edit-mode editable ng-untouched ng-pristine ng-valid ng-star-inserted</value>
        <webElementGuid>3fbe5ab4-dbc2-4862-9285-5838d2c11232</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>role</name>
        <type>Main</type>
        <value>textbox</value>
        <webElementGuid>3fbe5ab4-dbc2-4862-9285-5838d2c11232</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>text</value>
        <webElementGuid>3fbe5ab4-dbc2-4862-9285-5838d2c11232</webElementGuid>
    </webElementProperties>
</WebElementEntity>