<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>d804e2de-a356-4355-a103-b802696e38c0</elementGuidId>
    <imagePath></imagePath>
    <name>button_picker</name>
    <selectorCollection>
        <entry>
            <key>CSS</key>
            <value>[class="picker-button\ ng-tns-c1728421794-1757\ dropdown-mode\ ng-star-inserted"]</value>
        </entry>
        <entry>
            <key>XPATH</key>
            <value>//body/fnd-app[1]/fnd-shell[1]/div[1]/fnd-modal-assistant[1]/fnd-dialog-container[1]/div[1]/div[2]/div[2]/fnd-assistant[1]/div[1]/div[1]/div[2]/div[1]/div[2]/div[1]/fnd-container[1]/fnd-group[1]/fnd-collapsible-group[1]/div[1]/div[1]/div[1]/fnd-input-field-container[1]/fnd-input-field[1]/div[1]/form[1]/div[2]/button[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'AddFromRepresentativeGroupAssistant-AddFromRepresentativeGroup-GroupId-pickerButton') and equals(@class,'picker-button ng-tns-c1728421794-1757 dropdown-mode ng-star-inserted') and equals(@type,'button')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>CSS</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>#AddFromRepresentativeGroupAssistant-AddFromRepresentativeGroup-GroupId-pickerButton</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>picker-button ng-tns-c1728421794-1757 dropdown-mode ng-star-inserted</value>
        <webElementGuid>e2db0501-2c78-406f-8baf-49615b148ebe</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>AddFromRepresentativeGroupAssistant-AddFromRepresentativeGroup-GroupId-pickerButton</value>
        <webElementGuid>e2db0501-2c78-406f-8baf-49615b148ebe</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>button</value>
        <webElementGuid>e2db0501-2c78-406f-8baf-49615b148ebe</webElementGuid>
    </webElementProperties>
</WebElementEntity>