<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>9bc1323b-ae12-423c-91bc-d0b430000956</elementGuidId>
    <imagePath></imagePath>
    <name>button_delete</name>
    <selectorCollection>
        <entry>
            <key>CSS</key>
            <value>[id="BusinessLeadDetailPage-fndToolbar-action-Delete-fndButton-button"]</value>
        </entry>
        <entry>
            <key>XPATH</key>
            <value>//body/fnd-app[1]/fnd-shell[1]/div[1]/div[3]/fnd-splitter[1]/div[1]/div[1]/div[1]/div[1]/section[1]/div[2]/fnd-page[1]/div[1]/fnd-splitter[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/fnd-container[1]/fnd-selector[1]/div[2]/fnd-toolbar[1]/div[1]/fnd-dynamic-toolbar[1]/fnd-overflow-container[1]/fnd-overflow-container[1]/fnd-overflow-container[2]/fnd-measure[4]/fnd-granite-button-wrapper[1]/button[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@title,'Delete selected record(s)')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>CSS</selectorMethod>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>false</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>granite-button-base granite-button-wrapper granite-button granite-flat-button ng-star-inserted</value>
        <webElementGuid>84a4e4a3-b371-4532-9f7e-b9cab76269fb</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>false</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>BusinessLeadDetailPage-fndToolbar-action-Delete-fndButton-button</value>
        <webElementGuid>84a4e4a3-b371-4532-9f7e-b9cab76269fb</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>Delete selected record(s)</value>
        <webElementGuid>84a4e4a3-b371-4532-9f7e-b9cab76269fb</webElementGuid>
    </webElementProperties>
</WebElementEntity>