<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>941c52ac-41a0-4898-be53-f44db7fe0e25</elementGuidId>
    <imagePath></imagePath>
    <name>div_businessLeadRepList</name>
    <selectorCollection>
        <entry>
            <key>CSS</key>
            <value>[id="BusinessLeadDetailPage-BusinessLeadRepList-fndRow-0-MainRepresentative"] .static-field-border-compensator</value>
        </entry>
        <entry>
            <key>XPATH</key>
            <value>//body/fnd-app[1]/fnd-shell[1]/div[1]/div[3]/fnd-splitter[1]/div[1]/div[1]/div[1]/div[1]/section[1]/div[2]/fnd-page[1]/div[1]/fnd-splitter[1]/div[2]/div[2]/div[2]/fnd-container[1]/fnd-tab-container[1]/fnd-tab-control[1]/div[1]/fnd-tab-content[3]/fnd-container[2]/fnd-list[1]/fnd-collapsible-group[1]/div[1]/div[1]/div[1]/fnd-data-list[1]/div[3]/div[2]/fnd-row[1]/fnd-cell[1]/div[1]/div[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'static-field-border-compensator')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>CSS</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>#BusinessLeadDetailPage-BusinessLeadRepList-fndRow-0-MainRepresentative div &gt;&gt; nth=1</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>static-field-border-compensator</value>
        <webElementGuid>e2db0501-2c78-406f-8baf-49615b148ebe</webElementGuid>
    </webElementProperties>
</WebElementEntity>