<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>d6a2bf36-88fa-4a57-a60a-c31d3b15c7e6</elementGuidId>
    <imagePath></imagePath>
    <name>input_defaultLanguage</name>
    <selectorCollection>
        <entry>
            <key>CSS</key>
            <value>[class="ng-tns-c1728421794-1499\ ifs-field\ ifs-field-hover\ ng-untouched\ ng-pristine\ ng-star-inserted\ editable\ haspicker\ ng-valid\ edit-mode"]</value>
        </entry>
        <entry>
            <key>XPATH</key>
            <value>//body/fnd-app[1]/fnd-shell[1]/div[1]/div[3]/fnd-splitter[1]/div[1]/div[1]/div[1]/div[1]/section[1]/div[2]/fnd-page[1]/div[1]/fnd-splitter[1]/div[2]/div[2]/div[1]/fnd-container[1]/fnd-group[1]/fnd-collapsible-group[1]/div[1]/div[1]/div[1]/fnd-input-field-container[4]/fnd-input-field[1]/div[1]/form[1]/div[2]/div[1]/div[1]/input[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@type,'text') and equals(@role,'textbox')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>CSS</selectorMethod>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>false</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>ng-tns-c1728421794-1499 ifs-field ifs-field-hover ng-untouched ng-pristine ng-star-inserted editable haspicker ng-valid edit-mode</value>
        <webElementGuid>84a4e4a3-b371-4532-9f7e-b9cab76269fb</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>role</name>
        <type>Main</type>
        <value>textbox</value>
        <webElementGuid>84a4e4a3-b371-4532-9f7e-b9cab76269fb</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>text</value>
        <webElementGuid>84a4e4a3-b371-4532-9f7e-b9cab76269fb</webElementGuid>
    </webElementProperties>
</WebElementEntity>