<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>18c5bec7-a0e9-4f5f-b1ec-efc2d800ec40</elementGuidId>
    <imagePath></imagePath>
    <name>textarea_note2</name>
    <selectorCollection>
        <entry>
            <key>CSS</key>
            <value>.focused</value>
        </entry>
        <entry>
            <key>XPATH</key>
            <value>//body/fnd-app[1]/fnd-shell[1]/div[1]/fnd-modal-dialog[1]/fnd-dialog-container[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[1]/fnd-group[1]/fnd-collapsible-group[1]/div[1]/div[1]/div[1]/fnd-input-field-container[1]/fnd-input-field[1]/div[1]/form[1]/div[2]/textarea[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'cdk-textarea-autosize ifs-field ifs-textarea ifs-field-hover ng-tns-c1728421794-1586 edit-mode editable ng-untouched ng-pristine ng-valid ng-star-inserted focused')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>CSS</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:label=\"Note\"s</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>cdk-textarea-autosize ifs-field ifs-textarea ifs-field-hover ng-tns-c1728421794-1586 edit-mode editable ng-untouched ng-pristine ng-valid ng-star-inserted focused</value>
        <webElementGuid>e2db0501-2c78-406f-8baf-49615b148ebe</webElementGuid>
    </webElementProperties>
</WebElementEntity>