<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>button_apply</name>
   <tag></tag>
   <elementGuidId>4ce22854-e35a-4a8e-86c9-40ee33d962de</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/fnd-app[1]/fnd-shell[1]/div[1]/fnd-modal-assistant[1]/fnd-dialog-container[1]/div[1]/div[2]/div[2]/fnd-assistant[1]/div[1]/div[1]/div[2]/div[1]/div[2]/div[1]/fnd-container[1]/fnd-list[1]/fnd-collapsible-group[1]/div[1]/div[1]/div[1]/fnd-data-list[1]/div[2]/div[2]/fnd-list-filter-pane[1]/div[1]/div[1]/fnd-search-actions-panel[1]/div[1]/fnd-search-action-button[1]/button[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[equals(@title,'Search') and equals(@text,'Apply')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[class="granite-button-base\ granite-button\ search-button\ apply-button"]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=\", Current view mode - List\"s &gt;&gt; button[title=\"Search\"]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>granite-button-base granite-button search-button apply-button</value>
      <webElementGuid>a5439a7e-3c75-4750-8611-c3b6f4c39637</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Apply</value>
      <webElementGuid>a5439a7e-3c75-4750-8611-c3b6f4c39637</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>a5439a7e-3c75-4750-8611-c3b6f4c39637</webElementGuid>
   </webElementProperties>
</WebElementEntity>
