<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>button_logout</name>
   <tag></tag>
   <elementGuidId>33d0720b-87e0-42d8-a016-1100100d7917</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/div[1]/div[10]/div[1]/div[1]/div[1]/button[15]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[equals(@text,'logout
         Log out') and equals(@role,'menuitem')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button:nth-of-type(15)</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>button &gt;&gt; internal:text=\"logoutLog out\"s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>granite-menu-item granite-divider-top ng-tns-c1073040337-1 ng-star-inserted</value>
      <webElementGuid>ce743a67-f8d6-4398-9a64-18f996fa3314</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>ce743a67-f8d6-4398-9a64-18f996fa3314</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>logout
      Log out</value>
      <webElementGuid>ce743a67-f8d6-4398-9a64-18f996fa3314</webElementGuid>
   </webElementProperties>
</WebElementEntity>
