<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>99600c6c-8335-413c-a983-6103eee4102b</elementGuidId>
    <imagePath></imagePath>
    <name>div_search</name>
    <selectorCollection>
        <entry>
            <key>CSS</key>
            <value>[class="row-1\ ng-tns-c2368425041-2272"]</value>
        </entry>
        <entry>
            <key>XPATH</key>
            <value>//body/fnd-app[1]/fnd-shell[1]/div[1]/div[3]/fnd-splitter[1]/div[1]/div[1]/div[1]/div[1]/section[1]/div[2]/div[1]/fnd-search-panel[1]/div[1]/div[1]/div[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'row-1 ng-tns-c2368425041-2272') and equals(@text,'Search')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>CSS</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>.row-1</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>row-1 ng-tns-c2368425041-2272</value>
        <webElementGuid>e2db0501-2c78-406f-8baf-49615b148ebe</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Search</value>
        <webElementGuid>e2db0501-2c78-406f-8baf-49615b148ebe</webElementGuid>
    </webElementProperties>
</WebElementEntity>