<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>09301aaf-669e-47f9-b042-797471f33d30</elementGuidId>
    <imagePath></imagePath>
    <name>textarea_search</name>
    <selectorCollection>
        <entry>
            <key>CSS</key>
            <value>[class="ng-tns-c2368425041-2304\ ng-untouched\ ng-pristine\ ng-valid"]</value>
        </entry>
        <entry>
            <key>XPATH</key>
            <value>//body/fnd-app[1]/fnd-shell[1]/div[1]/div[3]/fnd-splitter[1]/div[1]/div[1]/div[1]/div[1]/section[1]/div[2]/div[1]/fnd-search-panel[1]/div[1]/div[1]/div[2]/div[2]/div[1]/textarea[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'ng-tns-c2368425041-2304 ng-untouched ng-pristine ng-valid') and equals(@title,'Ctrl+Enter to search') and equals(@type,'text')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>CSS</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>textarea[title=\"Ctrl\\+Enter to search\"]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>ng-tns-c2368425041-2304 ng-untouched ng-pristine ng-valid</value>
        <webElementGuid>e2db0501-2c78-406f-8baf-49615b148ebe</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>Ctrl+Enter to search</value>
        <webElementGuid>e2db0501-2c78-406f-8baf-49615b148ebe</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>text</value>
        <webElementGuid>e2db0501-2c78-406f-8baf-49615b148ebe</webElementGuid>
    </webElementProperties>
</WebElementEntity>