<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>label_australia</name>
   <tag></tag>
   <elementGuidId>0819ed50-e418-43c1-a1a6-05b8a3135a38</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/fnd-app[1]/fnd-shell[1]/div[1]/fnd-adjacent-container[1]/div[1]/fnd-adjacent-content[1]/fnd-keep-within-viewport[1]/div[1]/div[1]/fnd-dropdown[1]/fnd-menu[1]/ul[1]/li[1]/fnd-menu-select-item[1]/div[1]/fnd-menu-item[1]/div[1]/label[1]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(1) .item-label</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = ' AUSTRALIA ' or . = ' AUSTRALIA ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>label >> internal:text=&quot;AUSTRALIA&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>_ngcontent-ng-c3888462963</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>4550ae8d-e4c7-4819-ba65-9c6596556617</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>item-label ng-star-inserted</value>
      <webElementGuid>4550ae8d-e4c7-4819-ba65-9c6596556617</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> AUSTRALIA </value>
      <webElementGuid>4550ae8d-e4c7-4819-ba65-9c6596556617</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-area-wrapper']/fnd-adjacent-container/div/fnd-adjacent-content/fnd-keep-within-viewport/div/div/fnd-dropdown/fnd-menu/ul/li/fnd-menu-select-item/div/fnd-menu-item/div/label</value>
      <webElementGuid>4550ae8d-e4c7-4819-ba65-9c6596556617</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label</value>
      <webElementGuid>4550ae8d-e4c7-4819-ba65-9c6596556617</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
