<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>878d62f5-54bd-4edf-8aee-4af5da1f4905</elementGuidId>
    <imagePath></imagePath>
    <name>input_country</name>
    <selectorCollection>
        <entry>
            <key>CSS</key>
            <value>[class="ng-tns-c1728421794-2100\ ifs-field\ ifs-field-hover\ detail-page\ ng-untouched\ ng-pristine\ ng-valid\ edit-mode\ editable\ haspicker\ ng-star-inserted"]</value>
        </entry>
        <entry>
            <key>XPATH</key>
            <value>//body/fnd-app[1]/fnd-shell[1]/div[1]/div[3]/fnd-splitter[1]/div[1]/div[1]/div[1]/div[1]/section[1]/div[2]/fnd-assistant[1]/div[1]/div[1]/div[2]/div[1]/div[2]/div[1]/fnd-container[1]/fnd-group[1]/fnd-collapsible-group[1]/div[1]/div[1]/div[1]/fnd-input-field-container[7]/fnd-input-field[1]/div[1]/form[1]/div[2]/div[1]/div[1]/input[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@type,'text') and equals(@role,'combobox')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>CSS</selectorMethod>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>false</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>ng-tns-c1728421794-2100 ifs-field ifs-field-hover detail-page ng-untouched ng-pristine ng-valid edit-mode editable haspicker ng-star-inserted</value>
        <webElementGuid>30bd2636-b893-46cf-b979-1d33007ac79b</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>role</name>
        <type>Main</type>
        <value>combobox</value>
        <webElementGuid>30bd2636-b893-46cf-b979-1d33007ac79b</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>text</value>
        <webElementGuid>30bd2636-b893-46cf-b979-1d33007ac79b</webElementGuid>
    </webElementProperties>
</WebElementEntity>