<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>47952386-e870-4fa4-a01f-b39c4cda8049</elementGuidId>
    <imagePath></imagePath>
    <name>button_logout</name>
    <selectorCollection>
        <entry>
            <key>CSS</key>
            <value>button:nth-of-type(15)</value>
        </entry>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[10]/div[1]/div[1]/div[1]/button[15]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'logout
            Log out') and equals(@role,'menuitem')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>CSS</selectorMethod>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>false</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>granite-menu-item granite-divider-top ng-tns-c1073040337-1 ng-star-inserted</value>
        <webElementGuid>3fbe5ab4-dbc2-4862-9285-5838d2c11232</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>role</name>
        <type>Main</type>
        <value>menuitem</value>
        <webElementGuid>3fbe5ab4-dbc2-4862-9285-5838d2c11232</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>logout
        Log out</value>
        <webElementGuid>3fbe5ab4-dbc2-4862-9285-5838d2c11232</webElementGuid>
    </webElementProperties>
</WebElementEntity>