<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>f0996bef-8c49-444d-b67b-91f9049552f8</elementGuidId>
    <imagePath></imagePath>
    <name>label_lessThan10</name>
    <selectorCollection>
        <entry>
            <key>CSS</key>
            <value>body:nth-of-type(1) &gt; fnd-app:nth-of-type(1) &gt; fnd-shell:nth-of-type(1) &gt; div:nth-of-type(1) &gt; fnd-adjacent-container:nth-of-type(1) &gt; div:nth-of-type(1) &gt; fnd-adjacent-content:nth-of-type(1) &gt; fnd-keep-within-viewport:nth-of-type(1) &gt; div:nth-of-type(1) &gt; div:nth-of-type(1) &gt; fnd-dropdown:nth-of-type(1) &gt; fnd-menu:nth-of-type(1) &gt; ul:nth-of-type(1) &gt; li:nth-of-type(1) &gt; fnd-menu-select-item:nth-of-type(1) &gt; div:nth-of-type(1) &gt; fnd-menu-item:nth-of-type(1) &gt; div:nth-of-type(1) &gt; label:nth-of-type(1)</value>
        </entry>
        <entry>
            <key>XPATH</key>
            <value>//body/fnd-app[1]/fnd-shell[1]/div[1]/fnd-adjacent-container[1]/div[1]/fnd-adjacent-content[1]/fnd-keep-within-viewport[1]/div[1]/div[1]/fnd-dropdown[1]/fnd-menu[1]/ul[1]/li[1]/fnd-menu-select-item[1]/div[1]/fnd-menu-item[1]/div[1]/label[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,' &lt;10 ')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>CSS</selectorMethod>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>false</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>item-label ng-star-inserted</value>
        <webElementGuid>3bd89cf4-7f59-42be-aaa7-b057fbbf5ef7</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value> &lt;10 </value>
        <webElementGuid>3bd89cf4-7f59-42be-aaa7-b057fbbf5ef7</webElementGuid>
    </webElementProperties>
</WebElementEntity>