<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>5c2c9125-61ad-40b5-a32e-45e806cdebd9</elementGuidId>
    <imagePath></imagePath>
    <name>link_details</name>
    <selectorCollection>
        <entry>
            <key>CSS</key>
            <value>[id="CrmCustomerPage-BusinessOpportunitiesList-fndRow-0-fndCommandCell-fndCommandDropdown-fndMenu-Details-fndButton-button"]</value>
        </entry>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[11]/div[1]/div[1]/div[1]/div[1]/fnd-granite-button-wrapper[1]/a[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'granite-button-base granite-button-anchor-wrapper granite-button granite-flat-button ng-star-inserted') and equals(@text,'Details')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>CSS</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>#CrmCustomerPage-BusinessOpportunitiesList-fndRow-0-fndCommandCell-fndCommandDropdown-fndMenu-Details-fndButton-button</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>granite-button-base granite-button-anchor-wrapper granite-button granite-flat-button ng-star-inserted</value>
        <webElementGuid>e2db0501-2c78-406f-8baf-49615b148ebe</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Details</value>
        <webElementGuid>e2db0501-2c78-406f-8baf-49615b148ebe</webElementGuid>
    </webElementProperties>
</WebElementEntity>