<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>4e946232-f5d3-4ee7-8e50-ecd246425d86</elementGuidId>
    <imagePath></imagePath>
    <name>link_accountStructure</name>
    <selectorCollection>
        <entry>
            <key>CSS</key>
            <value>[id="CrmCustomerPage-CrmCompanyRelationsList-fndDataGridToolbar-fndToolbar-action-fndButton-CrmCompanyRelationsList_NavigateToChildAccountStructureCommand-button"]</value>
        </entry>
        <entry>
            <key>XPATH</key>
            <value>//body/fnd-app[1]/fnd-shell[1]/div[1]/div[3]/fnd-splitter[1]/div[1]/div[1]/div[1]/div[1]/section[1]/div[2]/fnd-page[1]/div[1]/fnd-splitter[1]/div[2]/div[2]/div[2]/fnd-container[1]/fnd-tab-container[1]/fnd-tab-control[1]/div[1]/fnd-tab-content[1]/fnd-container[3]/fnd-list[1]/fnd-collapsible-group[1]/div[1]/div[1]/div[1]/fnd-data-list[1]/div[2]/div[1]/fnd-data-grid-toolbar[1]/div[1]/fnd-toolbar[1]/div[1]/fnd-dynamic-toolbar[1]/fnd-overflow-container[1]/fnd-overflow-container[1]/fnd-overflow-container[5]/fnd-measure[1]/fnd-granite-button-wrapper[1]/a[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@title,'Account Structure')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>CSS</selectorMethod>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>false</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>granite-button-base granite-button-anchor-wrapper granite-button granite-toolbar-button ng-star-inserted</value>
        <webElementGuid>30bd2636-b893-46cf-b979-1d33007ac79b</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>false</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>CrmCustomerPage-CrmCompanyRelationsList-fndDataGridToolbar-fndToolbar-action-fndButton-CrmCompanyRelationsList_NavigateToChildAccountStructureCommand-button</value>
        <webElementGuid>30bd2636-b893-46cf-b979-1d33007ac79b</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>Account Structure</value>
        <webElementGuid>30bd2636-b893-46cf-b979-1d33007ac79b</webElementGuid>
    </webElementProperties>
</WebElementEntity>