<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>link_schedulingOptimizationDatasets</name>
   <tag></tag>
   <elementGuidId>82addf2d-348d-4071-902a-3857c390aa12</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/div[1]/div[11]/div[1]/div[1]/div[1]/div[2]/fnd-granite-button-wrapper[1]/a[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[equals(@title,'Scheduling Optimization Datasets') and equals(@text,'Scheduling Optimization Datasets')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[id="PsoIntegrationConfigurations-PsoIntegrationConfigurations-fndRow-0-fndCommandCell-fndCommandDropdown-fndMenu-fndButton-PsoIntegrationConfigurations_CommandDatasets-button"]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#PsoIntegrationConfigurations-PsoIntegrationConfigurations-fndRow-0-fndCommandCell-fndCommandDropdown-fndMenu-fndButton-PsoIntegrationConfigurations_CommandDatasets-button</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>granite-button-base granite-button-anchor-wrapper granite-button ng-star-inserted</value>
      <webElementGuid>5714b90b-59ba-4213-9ca5-c17d0766999b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Scheduling Optimization Datasets</value>
      <webElementGuid>5714b90b-59ba-4213-9ca5-c17d0766999b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Scheduling Optimization Datasets</value>
      <webElementGuid>5714b90b-59ba-4213-9ca5-c17d0766999b</webElementGuid>
   </webElementProperties>
</WebElementEntity>
