<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>b0a20cc1-b4e1-4e7e-8485-dd4ab96d978d</elementGuidId>
    <imagePath></imagePath>
    <name>button_picker</name>
    <selectorCollection>
        <entry>
            <key>CSS</key>
            <value>[class="picker-button\ ng-tns-c1728421794-1792\ dropdown-mode\ list-field\ compact-date-field-icon\ ng-star-inserted"]</value>
        </entry>
        <entry>
            <key>XPATH</key>
            <value>//body/fnd-app[1]/fnd-shell[1]/div[1]/div[3]/fnd-splitter[1]/div[1]/div[1]/div[1]/div[1]/section[1]/div[2]/fnd-page[1]/div[1]/fnd-splitter[1]/div[2]/div[2]/div[2]/fnd-container[1]/fnd-tab-container[1]/fnd-tab-control[1]/div[1]/fnd-tab-content[2]/fnd-container[4]/fnd-list[1]/fnd-collapsible-group[1]/div[1]/div[1]/div[1]/fnd-data-list[1]/div[3]/div[2]/fnd-row[1]/fnd-cell[2]/fnd-input-field-container[1]/fnd-input-field[1]/div[1]/form[1]/div[2]/button[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@type,'button')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>CSS</selectorMethod>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>false</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>picker-button ng-tns-c1728421794-1792 dropdown-mode list-field compact-date-field-icon ng-star-inserted</value>
        <webElementGuid>3fbe5ab4-dbc2-4862-9285-5838d2c11232</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>button</value>
        <webElementGuid>3fbe5ab4-dbc2-4862-9285-5838d2c11232</webElementGuid>
    </webElementProperties>
</WebElementEntity>