<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>167d42b6-0b3f-4eec-8b80-d381d5522aa2</elementGuidId>
    <imagePath></imagePath>
    <name>button_delete</name>
    <selectorCollection>
        <entry>
            <key>CSS</key>
            <value>[id="OpportunityDetailPage-CompetitorList-fndDataGridToolbar-fndToolbar-action-Delete-fndButton-button"]</value>
        </entry>
        <entry>
            <key>XPATH</key>
            <value>//body/fnd-app[1]/fnd-shell[1]/div[1]/div[3]/fnd-splitter[1]/div[1]/div[1]/div[1]/div[1]/section[1]/div[2]/fnd-page[1]/div[1]/fnd-splitter[1]/div[2]/div[2]/div[2]/fnd-container[1]/fnd-tab-container[1]/fnd-tab-control[1]/div[1]/fnd-tab-content[2]/fnd-container[4]/fnd-list[1]/fnd-collapsible-group[1]/div[1]/div[1]/div[1]/fnd-data-list[1]/div[2]/div[1]/fnd-data-grid-toolbar[1]/div[1]/fnd-toolbar[1]/div[1]/fnd-dynamic-toolbar[1]/fnd-overflow-container[1]/fnd-overflow-container[1]/fnd-overflow-container[2]/fnd-measure[4]/fnd-granite-button-wrapper[1]/button[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@title,'Delete selected record(s)')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>CSS</selectorMethod>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>false</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>granite-button-base granite-button-wrapper granite-button granite-flat-button ng-star-inserted</value>
        <webElementGuid>3fbe5ab4-dbc2-4862-9285-5838d2c11232</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>false</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>OpportunityDetailPage-CompetitorList-fndDataGridToolbar-fndToolbar-action-Delete-fndButton-button</value>
        <webElementGuid>3fbe5ab4-dbc2-4862-9285-5838d2c11232</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>Delete selected record(s)</value>
        <webElementGuid>3fbe5ab4-dbc2-4862-9285-5838d2c11232</webElementGuid>
    </webElementProperties>
</WebElementEntity>