<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>c77f7c7b-2ae4-4d17-8f65-521f63fe01a4</elementGuidId>
    <imagePath></imagePath>
    <name>div_description</name>
    <selectorCollection>
        <entry>
            <key>CSS</key>
            <value>body:nth-of-type(1) &gt; fnd-app:nth-of-type(1) &gt; fnd-shell:nth-of-type(1) &gt; div:nth-of-type(1) &gt; fnd-modal-assistant:nth-of-type(1) &gt; fnd-dialog-container:nth-of-type(1) &gt; div:nth-of-type(1) &gt; div:nth-of-type(2) &gt; div:nth-of-type(2) &gt; fnd-assistant:nth-of-type(1) &gt; div:nth-of-type(1) &gt; div:nth-of-type(1) &gt; div:nth-of-type(2) &gt; div:nth-of-type(1) &gt; div:nth-of-type(2) &gt; div:nth-of-type(1) &gt; fnd-container:nth-of-type(1) &gt; fnd-list:nth-of-type(1) &gt; fnd-collapsible-group:nth-of-type(1) &gt; div:nth-of-type(1) &gt; div:nth-of-type(1) &gt; div:nth-of-type(1) &gt; fnd-data-list:nth-of-type(1) &gt; div:nth-of-type(2) &gt; div:nth-of-type(2) &gt; fnd-list-filter-pane:nth-of-type(1) &gt; div:nth-of-type(1) &gt; div:nth-of-type(1) &gt; fnd-field-filter:nth-of-type(2) &gt; div:nth-of-type(1) &gt; fnd-filter-badge:nth-of-type(1) &gt; fnd-filter-badge-content:nth-of-type(1) &gt; div:nth-of-type(1) &gt; div:nth-of-type(1)</value>
        </entry>
        <entry>
            <key>XPATH</key>
            <value>//body/fnd-app[1]/fnd-shell[1]/div[1]/fnd-modal-assistant[1]/fnd-dialog-container[1]/div[1]/div[2]/div[2]/fnd-assistant[1]/div[1]/div[1]/div[2]/div[1]/div[2]/div[1]/fnd-container[1]/fnd-list[1]/fnd-collapsible-group[1]/div[1]/div[1]/div[1]/fnd-data-list[1]/div[2]/div[2]/fnd-list-filter-pane[1]/div[1]/div[1]/fnd-field-filter[2]/div[1]/fnd-filter-badge[1]/fnd-filter-badge-content[1]/div[1]/div[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@title,'Description') and equals(@text,'Description')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>CSS</selectorMethod>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>false</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>header-label left</value>
        <webElementGuid>30bd2636-b893-46cf-b979-1d33007ac79b</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Description</value>
        <webElementGuid>30bd2636-b893-46cf-b979-1d33007ac79b</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>Description</value>
        <webElementGuid>30bd2636-b893-46cf-b979-1d33007ac79b</webElementGuid>
    </webElementProperties>
</WebElementEntity>