<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>4206bf8c-a2ca-4907-8a87-43295ac999e5</elementGuidId>
    <imagePath></imagePath>
    <name>i_dropdown</name>
    <selectorCollection>
        <entry>
            <key>CSS</key>
            <value>body:nth-of-type(1) &gt; fnd-app:nth-of-type(1) &gt; fnd-shell:nth-of-type(1) &gt; div:nth-of-type(1) &gt; div:nth-of-type(3) &gt; fnd-splitter:nth-of-type(1) &gt; div:nth-of-type(1) &gt; div:nth-of-type(1) &gt; div:nth-of-type(1) &gt; div:nth-of-type(1) &gt; section:nth-of-type(1) &gt; div:nth-of-type(2) &gt; fnd-page:nth-of-type(1) &gt; div:nth-of-type(1) &gt; fnd-splitter:nth-of-type(1) &gt; div:nth-of-type(2) &gt; div:nth-of-type(2) &gt; div:nth-of-type(4) &gt; fnd-container:nth-of-type(1) &gt; fnd-list:nth-of-type(1) &gt; fnd-collapsible-group:nth-of-type(1) &gt; div:nth-of-type(1) &gt; div:nth-of-type(1) &gt; div:nth-of-type(1) &gt; fnd-data-list:nth-of-type(1) &gt; div:nth-of-type(2) &gt; div:nth-of-type(2) &gt; fnd-list-filter-pane:nth-of-type(1) &gt; div:nth-of-type(1) &gt; div:nth-of-type(1) &gt; fnd-field-filter:nth-of-type(1) &gt; div:nth-of-type(1) &gt; fnd-filter-badge:nth-of-type(1) &gt; fnd-filter-badge-content:nth-of-type(1) &gt; div:nth-of-type(1) &gt; i:nth-of-type(1)</value>
        </entry>
        <entry>
            <key>XPATH</key>
            <value>//body/fnd-app[1]/fnd-shell[1]/div[1]/div[3]/fnd-splitter[1]/div[1]/div[1]/div[1]/div[1]/section[1]/div[2]/fnd-page[1]/div[1]/fnd-splitter[1]/div[2]/div[2]/div[4]/fnd-container[1]/fnd-list[1]/fnd-collapsible-group[1]/div[1]/div[1]/div[1]/fnd-data-list[1]/div[2]/div[2]/fnd-list-filter-pane[1]/div[1]/div[1]/fnd-field-filter[1]/div[1]/fnd-filter-badge[1]/fnd-filter-badge-content[1]/div[1]/i[1]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>CSS</selectorMethod>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>icon-triangle-down ng-star-inserted</value>
        <webElementGuid>30bd2636-b893-46cf-b979-1d33007ac79b</webElementGuid>
    </webElementProperties>
</WebElementEntity>