<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>616b4316-c689-4c7a-bf0a-34d55dfc4af2</elementGuidId>
    <imagePath></imagePath>
    <name>div_schedulingOptimizationDatasets</name>
    <selectorCollection>
        <entry>
            <key>CSS</key>
            <value>.current-element</value>
        </entry>
        <entry>
            <key>XPATH</key>
            <value>//body/fnd-app[1]/fnd-shell[1]/div[1]/div[3]/fnd-splitter[1]/fnd-sidebar-container[1]/div[1]/fnd-sidebar[1]/nav[1]/fnd-navigation-menu-controller[1]/fnd-submenu[1]/ul[1]/fnd-submenu-selectable-item[2]/div[1]/li[1]/div[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'Scheduling Optimization Datasets')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>CSS</selectorMethod>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>false</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>current-element</value>
        <webElementGuid>ee73da60-be40-4f65-8f74-dbba35950521</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Scheduling Optimization Datasets</value>
        <webElementGuid>ee73da60-be40-4f65-8f74-dbba35950521</webElementGuid>
    </webElementProperties>
</WebElementEntity>