<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>eb0c5183-ac2c-4655-a4a7-e8eec8793a76</elementGuidId>
    <imagePath></imagePath>
    <name>i_blowup4</name>
    <selectorCollection>
        <entry>
            <key>CSS</key>
            <value>body:nth-of-type(1) &gt; fnd-app:nth-of-type(1) &gt; fnd-shell:nth-of-type(1) &gt; div:nth-of-type(1) &gt; div:nth-of-type(3) &gt; fnd-splitter:nth-of-type(1) &gt; div:nth-of-type(1) &gt; div:nth-of-type(1) &gt; div:nth-of-type(1) &gt; div:nth-of-type(1) &gt; section:nth-of-type(1) &gt; div:nth-of-type(2) &gt; fnd-lobby-page:nth-of-type(1) &gt; div:nth-of-type(1) &gt; div:nth-of-type(2) &gt; div:nth-of-type(1) &gt; div:nth-of-type(1) &gt; fnd-lobby-renderer:nth-of-type(1) &gt; div:nth-of-type(1) &gt; div:nth-of-type(1) &gt; div:nth-of-type(4) &gt; div:nth-of-type(1) &gt; fnd-lobby-element:nth-of-type(1) &gt; div:nth-of-type(1) &gt; div:nth-of-type(1) &gt; div:nth-of-type(1) &gt; div:nth-of-type(2) &gt; div:nth-of-type(1) &gt; div:nth-of-type(1) &gt; i:nth-of-type(1)</value>
        </entry>
        <entry>
            <key>XPATH</key>
            <value>//body/fnd-app[1]/fnd-shell[1]/div[1]/div[3]/fnd-splitter[1]/div[1]/div[1]/div[1]/div[1]/section[1]/div[2]/fnd-lobby-page[1]/div[1]/div[2]/div[1]/div[1]/fnd-lobby-renderer[1]/div[1]/div[1]/div[4]/div[1]/fnd-lobby-element[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/i[1]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>CSS</selectorMethod>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>icon-blowup ng-star-inserted</value>
        <webElementGuid>3bd89cf4-7f59-42be-aaa7-b057fbbf5ef7</webElementGuid>
    </webElementProperties>
</WebElementEntity>