<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>8ecc388a-e075-43d0-a002-d44446469781</elementGuidId>
    <imagePath></imagePath>
    <name>link_schedulingOptimizationDatasets</name>
    <selectorCollection>
        <entry>
            <key>CSS</key>
            <value>[id="PsoIntegrationConfigurations-PsoIntegrationConfigurations-fndDataGridToolbar-fndToolbar-action-fndButton-PsoIntegrationConfigurations_CommandDatasets-button"]</value>
        </entry>
        <entry>
            <key>XPATH</key>
            <value>//body/fnd-app[1]/fnd-shell[1]/div[1]/div[3]/fnd-splitter[1]/div[1]/div[1]/div[1]/div[1]/section[1]/div[2]/fnd-page[1]/div[1]/fnd-splitter[1]/div[2]/div[2]/div[2]/fnd-container[1]/fnd-list[1]/fnd-collapsible-group[1]/div[1]/div[1]/div[1]/fnd-data-list[1]/div[2]/div[1]/fnd-data-grid-toolbar[1]/div[1]/fnd-toolbar[1]/div[1]/fnd-dynamic-toolbar[1]/fnd-overflow-container[1]/fnd-overflow-container[1]/fnd-overflow-container[4]/fnd-measure[1]/fnd-granite-button-wrapper[1]/a[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@title,'Scheduling Optimization Datasets') and equals(@text,'Scheduling Optimization Datasets')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>CSS</selectorMethod>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>false</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>granite-button-base granite-button-anchor-wrapper granite-button granite-toolbar-button ng-star-inserted</value>
        <webElementGuid>ee73da60-be40-4f65-8f74-dbba35950521</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>false</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>PsoIntegrationConfigurations-PsoIntegrationConfigurations-fndDataGridToolbar-fndToolbar-action-fndButton-PsoIntegrationConfigurations_CommandDatasets-button</value>
        <webElementGuid>ee73da60-be40-4f65-8f74-dbba35950521</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Scheduling Optimization Datasets</value>
        <webElementGuid>ee73da60-be40-4f65-8f74-dbba35950521</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>Scheduling Optimization Datasets</value>
        <webElementGuid>ee73da60-be40-4f65-8f74-dbba35950521</webElementGuid>
    </webElementProperties>
</WebElementEntity>